--CAR
CREATE TABLE CAR_TBL
(
    ID         NUMBER PRIMARY KEY,
    CAR_NUMBER NVARCHAR2(20),
    VIP        NUMBER(1),
    DELETED    NUMBER(1)
);

CREATE SEQUENCE CAR_SEQ INCREMENT BY 1;

--PARKING SPOT
CREATE TABLE PARKING_SPOT_TBL
(
    ID        NUMBER PRIMARY KEY,
    SPOT_NAME NVARCHAR2(10),
    STATUS    NUMBER(1),
    VIP       NUMBER(1),
    DELETED   NUMBER(1)
);

CREATE SEQUENCE PARKING_SPOT_SEQ INCREMENT BY 1;

--PARKING ENTRANCE
CREATE TABLE PARKING_ENTRANCE_TBL
(
    ID            NUMBER PRIMARY KEY,
    CAR_ID REFERENCES CAR_TBL,
    ENTRANCE_TIME TIMESTAMP,
    PARKING_SPOT_ID REFERENCES PARKING_SPOT_TBL,
    DELETED       NUMBER(1)
);

CREATE SEQUENCE PARKING_ENTRANCE_SEQ INCREMENT BY 1;

--PARKING BILL
CREATE TABLE PARKING_BILL_TABLE
(
    ID        NUMBER PRIMARY KEY,
    ENTRANCE_ID REFERENCES PARKING_ENTRANCE_TBL,
    EXIT_TIME TIMESTAMP,
    COST      NUMBER,
    DELETED   NUMBER(1)
);

CREATE SEQUENCE PARKING_BILL_SEQ INCREMENT BY 1;


CREATE VIEW PARKING_ENTRANCE_REPORT AS
SELECT C.ID            AS C_ID,
       C.CAR_NUMBER    AS C_NUMBER,
       C.VIP           AS C_VIP,
       C.DELETED       AS C_DELETED,
       E.ENTRANCE_TIME AS E_ENTIME,
       E.ID            AS E_ID,
       E.DELETED       AS E_DELETED,
       PS.ID           AS PS_ID,
       PS.SPOT_NAME    AS PS_NAME,
       PS.STATUS       AS PS_STATUS,
       PS.VIP          AS PS_VIP,
       PS.DELETED      AS PS_DELETED
FROM PARKING_ENTRANCE_TBL E,
     CAR_TBL C,
     PARKING_SPOT_TBL PS
WHERE C.ID = E.CAR_ID
  AND PS.ID = E.PARKING_SPOT_ID
ORDER BY ENTRANCE_TIME;



CREATE VIEW PARKING_BILL_REPORT AS
SELECT C.ID            AS C_ID,
       C.CAR_NUMBER    AS C_NUMBER,
       C.VIP           AS C_VIP,
       C.DELETED       AS C_DELETED,
       E.ENTRANCE_TIME AS E_ENTIME,
       E.ID            AS E_ID,
       E.DELETED       AS E_DELETED,
       B.ID            AS B_ID,
       B.COST          AS B_COST,
       B.EXIT_TIME     AS B_EXTIME,
       B.DELETED       AS B_DELETED,
       PS.ID           AS PS_ID,
       PS.SPOT_NAME    AS PS_NAME,
       PS.STATUS       AS PS_STATUS,
       PS.VIP          AS PS_VIP,
       PS.DELETED      AS PS_DELETED
FROM CAR_TBL C,
     PARKING_BILL_TABLE B,
     PARKING_ENTRANCE_TBL E,
     PARKING_SPOT_TBL PS
WHERE E.ID = B.ENTRANCE_ID
  AND C.ID = E.CAR_ID
  AND PS.ID = E.PARKING_SPOT_ID
ORDER BY ENTRANCE_TIME;

--USER
CREATE TABLE USER_PARKING_TBL
(
    ID            NUMBER PRIMARY KEY,
    NAME          NVARCHAR2(30),
    FAMILY        NVARCHAR2(30),
    USERNAME      NVARCHAR2(30),
    PASSWORD      NVARCHAR2(30),
    NATIONAL_CODE NVARCHAR2(30),
    STATUS        NUMBER(1),
    DELETED       NUMBER(1)
);

CREATE SEQUENCE USER_PARKING_SEQ INCREMENT BY 1;

--COST RATE
CREATE TABLE PARKING_COST_RATE
(
    ID                   NUMBER PRIMARY KEY,
    HOURLY_RATE          NUMBER,
    DAILY_RATE           NUMBER,
    HOLIDAYS_HOURLY_RATE NUMBER,
    ENTRANCE_FEE         NUMBER
);

CREATE SEQUENCE PARKING_COST_RATE_SEQ INCREMENT BY 1;

--LOG
CREATE TABLE LOG_PARKING_TBL
(
    ID            NUMBER PRIMARY KEY,
    ACTION        NVARCHAR2(30),
    DATA          NVARCHAR2(90),
    USER_ID REFERENCES USER_TBL,
    LOG_TIMESTAMP TIMESTAMP
);

CREATE SEQUENCE LOG_PARKING_SEQ INCREMENT BY 1;

CREATE VIEW LOG_REPORT AS
SELECT UP.ID            AS USER_ID,
       UP.NAME          AS U_NAME,
       UP.FAMILY        AS U_FAMILY,
       UP.USERNAME      AS U_USERNAME,
       UP.PASSWORD      AS U_PASSWORD,
       UP.NATIONAL_CODE AS U_NATIONAL_CODE,
       UP.STATUS        AS U_STATUS,
       UP.DELETED       AS U_DELETED,
       LP.ID            AS L_ID,
       LP.ACTION        AS ACTION,
       LP.DATA          AS DATA,
       LP.LOG_TIMESTAMP AS LOG_TIMESTAMP
FROM USER_PARKING_TBL UP,
     LOG_PARKING_TBL LP
WHERE UP.ID = LP.USER_ID
ORDER BY LOG_TIMESTAMP;